### ISSUE TITLE
Autocomplete persistence bug

### ISSUE THREAD

**Issue by BobStein** [smartystreets/jquery.liveaddress#57] opened 2017-06-23 18:52 UTC
The Autocomplete window will sometimes refuse to disappear. Took me a while to figure out when this happens.  Steps to reproduce:

1. Go to https://smartystreets.com/docs/plugins/website
2. Enter something on the address line, such as "123 foo". Autocomplete options appear.
3. Click outside the address line. Autocomplete options go away. 
4. Go back to the address line and type THE SAME THING "123 foo". 
5. Click outside the address line.  Autocomplete options do NOT go away. And there's no obvious way to make them go away, or stop covering up other fields.

Attached videos reproduce the problem in Chrome and Firefox. 
Attached screenshot in Chrome.

I wonder if this is connected to an ominous comment circa line 777, https://github.com/smartystreets/jquery.liveaddress/blob/master/src/jquery.liveaddress.js#L777, "The website owner is responsible for making sure that any changes to address field values raise the "change" event on that element."

Possible cause: the plugin is relying on the "change" event to hideAutocomplete. But if the contents of the field don't actually change, it may not get triggered. 

Possible solution: intercept the "blur" event and do a ui.hideAutocomplete() in the "right" circumstances (e.g. not when selecting from the autocomplete menu).

Is there a workaround? That is, avoiding this bug purely in application code?  The following didn't work: intercepting the "blur" event and deactivate / reactivate that addressID. It thwarted legitimate selection from the autocomplete menu.

[SmartyStreets Autocomplete Persistence bug.zip](https://github.com/smartystreets/jquery.liveaddress/files/1098723/SmartyStreets.Autocomplete.Persistence.bug.zip)
![screenshot 2017-06-23 14 51 08](https://user-images.githubusercontent.com/4650454/27496293-75b31300-5823-11e7-8163-037ba8254b77.png)

**Comment by camiblanch** [comment] 2017-08-08 20:45
Thanks for bringing this to our attention. I was able to replicate the bug with the information you provided. I like your suggestion but something is nudging me to double check that it doesn't interfere with other interactions. I'll take a look at this

**Comment by camiblanch** [comment] 2017-11-10 22:36
Looking at this more closely it appears the problem is this. Usually the autocomplete popup is closed when the input is blank or after a change is triggered. Because neither of those happen, the autocomplete popup is never closed. [Here](https://github.com/smartystreets/jquery.liveaddress/blob/master/src/jquery.liveaddress.js#L2793) is where it is usually closed

**Comment by camiblanch** [comment] 2018-10-01 20:07
This bug should be fixed now as of 5.1.19

**Closed by camiblanch** 2018-10-01 20:07 UTC
